export const DATA_REFRESH_THRESHOLD = 5 * 60 * 1000;

export const TABLE_CONSTANTS = [
  {
    id: 1,
    name: "users",
    label: "Users",
    endpoint: "/users",
    columns: [
      {
        id: "user_id",
        label: "ID",
        accessor: "user_id",
        sortable: true,
        span: 1,
      },
      {
        id: "username",
        label: "Username",
        accessor: "username",
        sortable: true,
        span: 2,
      },
      {
        id: "email",
        label: "Email",
        accessor: "email",
        sortable: true,
        span: 2,
      },
      {
        id: "role",
        label: "Role",
        accessor: "role",
        sortable: true,
        span: 1,
      },
      {
        id: "created_at",
        label: "Created At",
        accessor: "createdAt",
        sortable: true,
        span: 2,
      },
      {
        id: "updated_at",
        label: "Updated At",
        accessor: "updatedAt",
        sortable: true,
        span: 2,
      },
    ],
    defaultSortColumn: "user_id",
    defaultSortDirection: "asc",
  },
  {
    id: 2,
    name: "sensors",
    label: "Sensors",
    endpoint: "/sensors",
    columns: [
      {
        id: "sensor_id",
        label: "ID",
        accessor: "sensor_id",
        sortable: true,
        span: 2,
      },
      {
        id: "sensor_name",
        label: "Name",
        accessor: "sensor_name",
        sortable: true,
        span: 1,
      },
      {
        id: "location",
        label: "Location",
        accessor: "location",
        sortable: true,
        span: 2,
      },
      {
        id: "sensor_type",
        label: "Type",
        accessor: "sensor_type",
        sortable: true,
        span: 1,
      },
      {
        id: "is_active",
        label: "Active",
        accessor: "is_active",
        sortable: true,
        span: 1,
      },
      {
        id: "unit_id",
        label: "Unit ID",
        accessor: "unit_id",
        sortable: true,
        endpoint: "/units",
        span: 3,
      },
      {
        id: "created_at",
        label: "Created",
        accessor: "createdAt",
        sortable: true,
        span: 2,
      },
      {
        id: "updated_at",
        label: "Updated",
        accessor: "updatedAt",
        sortable: true,
        span: 2,
      },
    ],
    defaultSortColumn: "sensor_id",
    defaultSortDirection: "asc",
  },
  {
    id: 3,
    name: "units",
    label: "Units",
    endpoint: "/units",
    columns: [
      {
        id: "unit_id",
        label: "ID",
        accessor: "unit_id",
        sortable: true,
        span: 3,
      },
      {
        id: "unit_name",
        label: "Name",
        accessor: "unit_name",
        sortable: true,
        span: 2,
      },
      {
        id: "location",
        label: "Location",
        accessor: "location",
        sortable: true,
        span: 2,
      },
      {
        id: "created_at",
        label: "Created At",
        accessor: "createdAt",
        sortable: true,
        span: 2,
      },
      {
        id: "updated_at",
        label: "Updated At",
        accessor: "updatedAt",
        sortable: true,
        span: 2,
      },
    ],
    defaultSortColumn: "unit_id",
    defaultSortDirection: "asc",
  },
  {
    id: 4,
    name: "roles",
    label: "Roles",
    endpoint: "/roles",
    columns: [
      { id: "role_id", label: "ID", accessor: "role_id", sortable: true },
      {
        id: "role_name",
        label: "Name",
        accessor: "role_name",
        sortable: true,
        span: 3,
      },
      {
        id: "created_at",
        label: "Created At",
        accessor: "createdAt",
        sortable: true,
        span: 3,
      },
      {
        id: "updated_at",
        label: "Updated At",
        accessor: "updatedAt",
        sortable: true,
        span: 3,
      },
    ],
    defaultSortColumn: "role_id",
    defaultSortDirection: "asc",
  },
  {
    id: 5,
    name: "requestLogs",
    label: "Request Logs",
    endpoint: "/requestlogs",
    columns: [
      { id: "request_id", label: "ID", accessor: "request_id", sortable: true },
      {
        id: "ip_address",
        label: "IP Address",
        accessor: "ip_address",
        sortable: true,
        span: 2,
      },
      {
        id: "request_type",
        label: "Type",
        accessor: "request_type",
        sortable: true,
        span: 1,
      },
      {
        id: "endpoint",
        label: "Endpoint",
        accessor: "endpoint",
        sortable: true,
        span: 3,
      },
      {
        id: "timestamp",
        label: "Timestamp",
        accessor: "timestamp",
        sortable: true,
        span: 2,
      },
    ],
    defaultSortColumn: "request_id",
    defaultSortDirection: "asc",
  },
];
